### ISSUE TITLE
spring-boot compile failed due to -Xbootclasspath/p  no longer supported

### ISSUE THREAD

**Issue by mencywoo** [GoogleCloudPlatform/gke-bazel-demo#13]
During `make create`,  the bazel build failed with the following error message 
```
~/gke-bazel-demo (mency-sandbox)$ make create
Your active configuration is: [cloudshell-18634]
INFO: Invocation ID: 69a69ace-8ae7-471b-9309-79169793513a
INFO: SHA256 (https://github.com/bazelbuild/rules_typescript/archive/0.21.0.zip) = e4f51c408ed3278a3a1dd227564a69f293ae2ac4ae1564b3a6d2637ae9447b47
INFO: SHA256 (https://github.com/bazelbuild/rules_nodejs/archive/0.16.2.zip) = 9b72bb0aea72d7cbcfc82a01b1e25bf3d85f791e790ddec16c65e2d906382ee0
INFO: Repository rule 'io_bazel_rules_k8s' returned: {"remote": "https://github.com/bazelbuild/rules_k8s.git", "commit": "bc9a60a1250af9856c4797aebd79bb08bee370f5", "shallow_since": "2018-12-21", "init_submodules": False, "verbose": False, "strip_prefix": "", "patches": [], "patch_tool": "patch", "patch_args": ["-p0"], "patch_cmds": [], "name": "io_bazel_rules_k8s"}
INFO: Repository rule 'io_bazel_rules_scala' returned: {"remote": "git://github.com/bazelbuild/rules_scala", "commit": "326b4ce252c36aeff2232e241ff4bfd8d6f6e071", "shallow_since": "2018-12-18", "init_submodules": False, "verbose": False, "strip_prefix": "", "patches": [], "patch_tool": "patch", "patch_args": ["-p0"], "patch_cmds": [], "name": "io_bazel_rules_scala"}
INFO: Repository rule 'java_image_base' returned: {"registry": "gcr.io", "repository": "distroless/java", "digest": "sha256:84740ded6cbeebaa89c9b19aed3754d464586592b561e5494be4192ac0b3a8f5", "tag": "latest", "os": "linux", "os_version": "", "os_features": [], "architecture": "amd64", "cpu_variant": "", "platform_features": [], "docker_client_config": "", "_puller": Label("@puller//file:downloaded")}
INFO: Analysed target //java-spring-boot:k8s.apply (96 packages loaded, 929 targets configured).
INFO: Found 1 target...
ERROR: /home/mency/gke-bazel-demo/java-spring-boot/BUILD.bazel:30:1: Building java-spring-boot/libtodo.jar (1 source file) failed: Worker process returned an unparseable WorkResponse!

Did you try to print something to stdout? Workers aren't allowed to do this, as it breaks the protocol between Bazel and the worker process.

---8<---8<--- Exception details ---8<---8<---
com.google.protobuf.InvalidProtocolBufferException$InvalidWireTypeException: Protocol message tag had invalid wire type.
        at com.google.protobuf.InvalidProtocolBufferException.invalidWireType(InvalidProtocolBufferException.java:115)
...
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$800(SkyframeActionExecutor.java:125)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:778)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:733)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:495)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:536)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:211)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:422)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
---8<---8<--- End of exception details ---8<---8<---
---8<---8<--- Start of log ---8<---8<---
-Xbootclasspath/p is no longer a supported option.
ion.
---8<---8<--- End of log ---8<---8<---
Target //java-spring-boot:k8s.apply failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 110.252s, Critical Path: 6.89s
INFO: 5 processes: 5 linux-sandbox.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
Makefile:40: recipe for target 'create' failed
make: *** [create] Error 1
```

This error has been observed on 
- MacOS 
- CloudShell

with JDK versions
- 1.8.0_180
- 1.8.0_202

**Comment by chrislovecnm** [comment]
This should be fixed
